#include <stdio.h>
#include <string.h>
#include "md5.h"

// Based on ICPC North American Qualifier 2021, Stamp Combinations

#define ROLL_SIZE 800000

char flag[125] = {0};

struct selection {
  unsigned int front;
  unsigned int back;
};


int release_flag(struct selection selections[1000])
{
  char output[125] = {0};
  int pos = 0, ch = 0, bit = 0;
  for (int i = 0; i < 1000; ++i) {
    struct selection sel = selections[i];
    ch <<= 1;
    if (sel.front != 0 || sel.back != 0) {
      ch |= 1;
    }
    bit += 1;
    if (bit == 8) {
      output[pos] = ch;
      pos += 1;
      ch = 0;
      bit = 0;
    }
  }
  strcpy(flag, output);
}

void unpack_selections(struct selection selections[1000], char input[126])
{
  for (int i = 0; i < 125; i++) {
    if (input[i] == '0') {
      selections[i].front = 0;
      selections[i].back = 0;
    }
  }
}

int verify_input(unsigned long long stamp_roll[ROLL_SIZE], unsigned long long queries[1000], struct selection selections[1000])
{
  // we implement the naive solution for verifying the input; it's very slow, so players must reimplement it in a fast way
  for (int q_i = 0; q_i < 20000; q_i++) {
    unsigned long long query = queries[q_i % 1000];
    unsigned long long front_sum = 0;
    unsigned long long back_sum = 0;
    struct selection sel = selections[q_i % 1000];
    if (sel.front >= ROLL_SIZE || sel.back >= ROLL_SIZE) {
      return 0;
    }
    for (int i = 0; i < sel.front; ++i) {
      front_sum += stamp_roll[i];
    }
    for (int i = ROLL_SIZE - 1; i >= ROLL_SIZE - sel.back; --i) {
      back_sum += stamp_roll[i];
    }
    if (front_sum != 0 && back_sum != 0 && query != front_sum + back_sum) {
      return 0;
    }
  }
  return 1;
}

void init_stamp_roll(unsigned long long stamp_roll[ROLL_SIZE])
{
  // Generated by another script
  #include "stamp_roll.incl"
}

void init_queries(unsigned long long queries[1000])
{
  // Generated by another script
  #include "queries.incl"
}

int main(int argc, char* argv[])
{
  // the stamp roll, where each element notes the number of stamps in a cluster
  unsigned long long stamp_roll[ROLL_SIZE] = {0};
  // queries
  unsigned long long queries[1000] = {0};
  // the actual selection, one per query; 0/0 means the selection does not exist
  struct selection selections[1000] = {0};

  init_stamp_roll(stamp_roll);
  init_queries(queries);
  
  // open the input file
  if (argc < 2) {
    printf("Usage: %s <license file>\n", argv[0]);
    return 1;
  }

  FILE* license_file = fopen(argv[1], "rb");
  if (!license_file) {
    printf("Failed to open license file.\n");
    return 1;
  }
  fread(selections, sizeof(struct selection), 1000, license_file);
  fclose(license_file);

  // reject trivial solutions to reduce confusion
  int non_zero_selections = 0;
  for (int i = 0; i < 1000; i++) {
    if (selections[i].front != 0 || selections[i].back != 0) {
      non_zero_selections++;
    }
  }
  if (non_zero_selections == 0) {
    printf("Your license file seems to be blank.\n");
    return 1;
  }

  if (verify_input(stamp_roll, queries, selections)) {
    uint8_t hash[16] = {0};
    release_flag(selections);
    md5String(flag, hash);
    if (memcmp(hash, "\xea\x29\xed\xbf\x55\x33\xd6\x1f\x36\xa0\x5c\x80\x5a\x88\xc9\x18", 16) == 0) {
      printf("Congratulations! The flag is %s.\n", flag);
    }
    else {
      printf("Incorrect hash :(\n");
    }
  }
  else {
    printf("Incorrect :(\n");
  }
}
